import 'package:hive_flutter/hive_flutter.dart';
import 'package:path_provider/path_provider.dart';

import '../models/project.dart';
import '../../core/app_constants.dart';

/// Initialises Hive and opens all required boxes.
/// Call [HiveDatabase.init] once at application startup before [runApp].
class HiveDatabase {
  HiveDatabase._();

  static bool _initialised = false;

  static Future<void> init() async {
    if (_initialised) return;

    // Locate a platform-appropriate local directory for Hive files.
    final appDocDir = await getApplicationDocumentsDirectory();
    await Hive.initFlutter(appDocDir.path);

    // Register all adapters (generated by hive_generator).
    if (!Hive.isAdapterRegistered(ProjectAdapter().typeId)) {
      Hive.registerAdapter(ProjectAdapter());
    }

    // Open boxes.
    await Hive.openBox<Project>(kProjectsBoxName);

    _initialised = true;
  }

  /// Gracefully close all boxes on app exit.
  static Future<void> close() async {
    await Hive.closeAllBoxes();
  }
}
